### ISSUE TITLE
Certain words lead to segmentation faults

### ISSUE THREAD

**Issue by Vuizur** [Dushistov/sdcv#81] opened 2022-06-04 08:15 UTC
I created a [Russian-Russian dictionary from Wiktionary](https://github.com/Vuizur/ruwiktionary-htmldump-parser/releases/download/v1.0.0/Russian-Russian-dict.zip), exported to stardict using pyglossary. For the majority of words it works fine, but for some words it crashes with a segmentation fault, for example for the words "и́менно" or "су́дно". 

When I use Goldendict to look up these words, then they are found correctly. The line endings of the ifo file are correct this time as far as I can tell.

**Comment by Dushistov** [comment] 2022-06-04 10:56
Are you sure that this is not duplicate of #79 , I tried your dictionary and works just fine:

```
❯ ./sdcv -u 'Русский Викисловарь (ru-ru)' 'и́менно'
Found 2 items, similar to и́менно.
0)Русский Викисловарь (ru-ru)-->Пи́мен
1)Русский Викисловарь (ru-ru)-->сме́нный
Your choice[-1 to abort]: 
```

Then I add your dictionary from #79 with line DOS line ending and I see crash.
Then I fixed line endings:
```
dos2unix /home/evgeniy/.stardict/dic/russian/russian.ifo
```
and all works without problems:
```
❯ ./sdcv и́менно | tee
Found 1 items, similar to и́менно.
-->Russian-English Dictionary (ru-en)!
-->и́менно

<p>just, exactly, actually; used to emphasize the meaning of the following word or what comes later and sometimes can be rather difficult to translate it in English.</p><p>namely, to wit, rather; used to specify something or when listing to specify something.</p><p>indeed, rather; used to emphasize the agreement or confirmation.</p>

```

**Comment by Vuizur** [comment] 2022-06-04 11:59
The problem with this newer (Ru-Ru) dictionary is that it does have LF file endings for the IFO file (at least according to VS code). So I don't know what I could fix. For my tests I used the interactive mode (using the version downloaded using ubuntu/apt),  maybe because of that I get different results. An example for strange behaviour would be:
```
pux@DESKTOP-L1488R9:/usr/share$ sdcv
Enter word or phrase: именно
Found 1 items, similar to именно.
-->Русский Викисловарь (ru-ru)
-->и́менно

<ul><li>частица выражает усиление, уточнение, решительное подтверждение <i>◆ Я видел тогда именно этого человека.    </i></li><li>союз вводит полное перечисление</li></ul>

Enter word or phrase: и́менно
Segmentation fault
```
So here it works when I look for the inflection (the dictionary contains именно as the inflection of и́менно), but not when I look for the lemma itself, unfortunately.

**Comment by ilius** [comment] 2022-06-21 11:31
If you remove or insert anything from/into `.dict` file, glossary will break, unless you update `.idx` file as well.

**Closed** 2022-06-24 18:34 UTC
